services:
  pg:
    image: postgres:16
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: botfactory
    ports: ["${PG_PORT}:5432"]
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d:ro
  redis:
    image: redis:7
    ports: ["${REDIS_PORT}:6379"]
  runtime:
    build:
      context: .
      dockerfile: docker/Dockerfile
    env_file: .env
    ports: ["8000:8000"]
    depends_on: [pg, redis]
volumes: { pgdata: {} }